version: '3.8'

volumes:
  pgdata: { }

services:
  tableGenius.api.web:
    image: peakcodedev/tablegenius-api
    ports:
      - "8181:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=development
      - DOTNET_ENVIRONMENT=development
    build:
      context: .
      dockerfile: Dockerfile
  
  tableGenius.db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ufo
      POSTGRES_DB: tableGenius
      POSTGRES_USER: ufo
    volumes:
      - pgdata:/var/lib/postgresql/data  
