#!/bin/bash
docker login -u $1 -p $2
actual_version="1.0.0"
echo $actual_version
docker build --platform linux/amd64 -f Dockerfile -t ursforrerch/tg-api:$actual_version .
docker push ursforrerch/tg-api:$actual_version
docker tag ursforrerch/tg-api:$actual_version ursforrerch/tg-api:latest
docker push ursforrerch/tg-api:latest
